### ISSUE TITLE
Feature Request - Invert filters

### ISSUE THREAD

**Issue by rayd99** [krbz999/babonus#105]
Example: The ability to apply a bonus if a given condition is not present (see DND5e Barbarian: Danger Sense. Advantage on DEX saving throws you can see, if the PC is not blinded, deafened, or incapacitated). Presently we can filter by conditions that are present, but no way to filter bonuses for if a condition is not present.

**Comment by krbz999** [comment]
Are there other examples, or is this possibly a duplicate of <https://github.com/krbz999/babonus/issues/37>?

**Comment by krbz999** [comment]
Should also note that Build-a-Bonus does not touch advantage and disadvantage.

**Comment by rayd99** [comment]
You are correct, this is a duplicate.
