### ISSUE TITLE
Possible "bug" with multiple conditions in one bab

### ISSUE THREAD

**Issue by Fridan99** [krbz999/babonus#107]
Foundry v10.291
System dnd5e 2.0.3
Build a bonus 10.3.2
Other modules deactivated: NO

I was trying to recreate the fell handed and shield feat UA, (_Whenever you have disadvantage on a melee attack roll you make with the weapon, you add a +5 bonus to the final result making it a possible success. Only affects to handaxe, battleaxe, mace, morningstar, and war pick_).

 **At the moment it is not possible to configure it with more filters in the bab**. so i set a bab as
- when the source is prone, blinded, exhaustion 3+
- when the target has invisible
- filter item Weapon

![1](https://user-images.githubusercontent.com/86131373/215226176-492965b1-0d3a-40d2-937c-950e1ef97263.jpg)

Configuring the bab, it seems that if I only apply one condition, the bab works.... but if I set two or more, it doesn't seem to add the bonus to hit.

If I create each condition separately as a new bab, it works..... but if I put several conditions in the same bab, it doesn't work.

I don't know if the intention of the module is to create each condition separately, or if it is finally some kind of bug.

**Comment by krbz999** [comment]
All the filters must evaluate to true for the bonus to apply. Therefore your current configuration is:
- "When you are blinded, exhausted, or prone, **_and_** the target is invisible, and you attack with a weapon, ..."

**Comment by Fridan99** [comment]
Ahhh now I understand, the target has to be invisible according to this configuration. So it must be invisible in a different bab, to not be a conditioner.

Also I seem to remember that with only the first config: blinded, prone or exhaust stopped working if I didn't apply them in a separately bab. I will test it again later. 

I understand that in order to be fulfilled it would have to be... blinded, prone **and** exhaust? or the intention of the module is blinded, prone **or** exhaust.

**Comment by krbz999** [comment]
I don't understand your questions. Anyway, how the module and filtering works is all explained in the tooltips.

![image](https://user-images.githubusercontent.com/50169243/215265303-c797c89b-2765-412b-b582-2d0b2f6db654.png)

![image](https://user-images.githubusercontent.com/50169243/215265319-75fa7e8a-66d9-4c78-a0da-bb0fa45e5c0b.png)

![image](https://user-images.githubusercontent.com/50169243/215265330-a6fa3c9c-2625-4eb0-980a-0943bc51a5f8.png)

**Comment by Fridan99** [comment]
I close the subject, the module works perfectly. I just tested it again without the invisible target, and it works perfectly. 
Sorry for the inconvenience :)
