### ISSUE TITLE
Request: Add damage type for damage bonuses.

### ISSUE THREAD

**Issue by MorganVergara** [krbz999/babonus#116]
As an example, a life stealer sword does 10 points of necrotic damage on a critical. This can be done with BaB, except for the damage type. If a creature is immune to necrotic damage, this should not apply. However, without the damage type, this immunity is effectively ignored, requiring the DM to have to undo the 10 points of critical damage.

**Comment by krbz999** [comment]
Well tell your module to stop applying it automatically then. :)
Or just label the +10 bonus with `[necrotic]` so your GM knows not to apply it on creatures that are immune.

It's not within scope of babonus to label rolls with damage types, when not even the system does that.

**Comment by MorganVergara** [comment]
The system does do that for base damage rolls on weapons (for example).

[image: image.png]

Of course, you're correct that it doesn't do that for other damage rolls,
such as extra critical damage, which I also consider a shortcoming in the
implementation, and have suggested should be corrected. That's actually why
I was hoping you would add the capability for BaB to possibly do it. You'd
be one step ahead of the actual system :)  Sadly, the labeling doesn't have
any actual in-game effect.

Of course, I don't know how difficult it would be. I'm not a Javascript
developer (I do C# and some bash scripting).

I'm the DM, and I like automation of things like this. I know there's a
fine line to automation in Foundry. I don't want to turn it into a video
game, but I do like the automation features it has, and was just suggesting
an improvement to it.

Anyways, thanks for hearing me out.

Take care!

Morgan

**Comment by krbz999** [comment]
For automation users such as yourself, I assume you use Midi or at the very least are relying on a module that requires you to target at all times. Sounds like what you want is already in the module in that case; the custom script filter should be all you need.
