### ISSUE TITLE
Reposition the + For Optional BaBs with Resource Consumption with Scaling

### ISSUE THREAD

**Issue by MaxPat931** [krbz999/babonus#128]
Current view

![image](https://user-images.githubusercontent.com/86370342/220042692-56d7ea16-432f-4422-b8bb-9a56d495f9f0.png)

I keep going straight to the drop down to select the number of charges, then click Normal without going back and clicking + to add the selection to the roll.

moving the + next to the dropdown would help the workflow in my opinion

![image](https://user-images.githubusercontent.com/86370342/220042385-2b324a9c-18f9-4ef8-8261-13d8e3e2644f.png)

**Comment by krbz999** [comment]
Maybe a horizontal rectangular button would be more ideal, and would work with both bonuses that consume and those that don't.

**Comment by krbz999** [comment]
[output.webm](https://user-images.githubusercontent.com/50169243/220432260-5277a09d-2c12-4bff-9613-12bbd57d761d.webm)

**Comment by MaxPat931** [comment]
Looks great!
