### ISSUE TITLE
Request: A filter for token size

### ISSUE THREAD

**Issue by GhostwheelX** [krbz999/babonus#148]
Might it be possible to add another filter that adds a size check for the target? Both one that is conditional on whether the target is smaller/larger/the same size as you, and if the target is at least Small or smaller, Huge or larger, etc., would be welcome.

**Comment by MaxPat931** [comment]
Might want to base it on the Height x Width of the token rather than the sheet's Size field to accommodate for edge cases like Enlarge/Reduce

**Comment by krbz999** [comment]
Is it unreasonable to assume that however people implement those features, they also change the value on the sheet?

**Comment by thatlonelybugbear** [comment]
I would say that Token configuration changes regarding "size", for example through modules like ATL/ATE will almost never be reflected to actor's character sheet size value... 😶‍🌫️ 

I always assume that the wider user base would not even think to link the two 🤷

**Comment by MaxPat931** [comment]
And if they aren't using ATE, then they are likely using a macro, and looking at macro-polo most of them just address the token size

CE's Enlarge Reduce does update the actor's size, but yea I dont think that it's something most people would do

**Comment by krbz999** [comment]
![image](https://user-images.githubusercontent.com/50169243/224483147-72217104-3c74-46bb-acf8-318958325545.png)

**Comment by MaxPat931** [comment]
Might be having a smooth brain moment here, but what does this 1.5 mean in this context? with and without "Compare to Self" on

**Comment by krbz999** [comment]
1.5 grid size
