### ISSUE TITLE
Request: Add filtering depending on the armor worn by the rolling actor

### ISSUE THREAD

**Issue by Kharmans** [krbz999/babonus#188]
Hey, what if Babonus could add bonus to movement, initiative and AC? That would be pretty cool.
And, like the filters of Weapon Properties and Weapon Types, would be cool if Babonus could add Armor Properties and Armor Types too. Like, the bonus only applied if the actor are using the Chain Mail, for example.

**Comment by InnilToo** [comment]
AC has been suggested here #73 and initiative here #167.

**Comment by thatlonelybugbear** [comment]
> 
FYI, you can already do that, using Custom Scripts.
```js
return !!actor.items.getName("Chain Mail")?.system.equipped;
```
This will return true if the actor has a Chain Mail item and is equipped.

**Comment by Kharmans** [comment]
The fighting style Defense: While you are wearing armor, you gain a +1 bonus to AC.
