### ISSUE TITLE
Fighting Style: Thrown Weapon Fighting

### ISSUE THREAD

**Issue by arcanjl** [krbz999/babonus#211]
"when you hit with a ranged attack using a thrown weapon, you gain a +2 bonus to the damage roll."

I can't seem to get this to work, is it beyond Buid a bonus?

**Comment by arcanjl** [comment]
Got it!

**Comment by krbz999** [comment]
For reference, this would be a Babonus of type "damage" with a bonus of "2" and with the filters:
* Item type: weapon
* Weapon properties: thrown (included)
* Attack types: rwak (ranged weapon attack)
Depending how you handle thrown weapons in your game of course.
