### ISSUE TITLE
Feature Request: Yeet the icon for non-GMs

### ISSUE THREAD

**Issue by LukasPrism** [krbz999/babonus#212]
Hi Zhell, hope you're well.

May I please kindly request a way for Babonus to only be available for GMs and not players? Something so powerful should not be in the hands of our group's players.

Thanks for your wonderful work, appreciate you.

L

**Comment by krbz999** [comment]
uwu

**Comment by krbz999** [comment]
## Implemented Feature
A new setting in the module settings which when false will cause the icon to not appear if the user is not a GM (default true).
