### ISSUE TITLE
Feature request: Add the option of additional weapon damage die

### ISSUE THREAD

**Issue by CrumpyPumpy** [krbz999/babonus#217]
For example: Like the dnd5e Bugbear's brute feature, which increases the damage die rolled for any weapon it wields by 1.

**Comment by krbz999** [comment]
One consideration to make here: Should a formula such as "1d6 + 1d4" be changed to "2d6 + 1d4" or "2d6 + 2d4"?

**Comment by InnilToo** [comment]
If we are adding damage die then we add them to the whole formula.
If we don't want that then we split the formulas (each for damage time) and filter out the damage time.

**Comment by krbz999** [comment]
This issue still needs clarification before it can be implemented.

**Comment by krbz999** [comment]
Or we can just do both. :-)
