### ISSUE TITLE
Syntax error in `abilities` filter.

### ISSUE THREAD

**Issue by nschoenwald** [krbz999/babonus#219]
I tried to implement the rage damage bonus and everything works until I try to filter for Strength attacks only.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/72390280/236797618-b9abfd24-9599-466a-ac67-2788deb476a6.png">

**Comment by InnilToo** [comment]
It's not supposed to work with RSR https://github.com/krbz999/babonus#compatibility

**Comment by nschoenwald** [comment]
RSR says it is verified compatible: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e#verified-modules

**Comment by GamerFlix** [comment]
Then you may want to talk zo RSR's dev since Build a bonus explicitly says that it doesn't even make an attempt to be compatible. If RSR's dev wishes for it to be compatible that'll have to be resolved on their side.

**Comment by GamerFlix** [comment]
Then you may want to talk to RSR's dev since Build a bonus explicitly says that it doesn't even make an attempt to be compatible. If RSR's dev wishes for it to be compatible that'll have to be resolved on their side.

**Comment by krbz999** [comment]
Actually there is a typo in the filter. :-)

**Comment by nschoenwald** [comment]
It works now, thanks a ton for the quick fix!
