### ISSUE TITLE
Bonus roll when actor has proficiency in the ability/skill rolled

### ISSUE THREAD

**Issue by louisr0608** [krbz999/babonus#241]
I was hoping to access the ability or skill type of the roll within the custom script. This is part of a class feature that would require checking to see if the actor has proficiency in the rolled ability to determine if they can roll with a bonus.

Thanks!

**Comment by krbz999** [comment]
I think an "isProficient" filter would be a good addition.

**Comment by louisr0608** [comment]
Thanks, that would be useful.

I've opened [https://github.com/krbz999/babonus/issues/242](url) to address the enhancement to the custom scripts.
