### ISSUE TITLE
Deprecate the 'Item Requirements' filter.

### ISSUE THREAD

**Issue by krbz999** [krbz999/babonus#254]
It's always been a weird one. Consider if it still has any value, and only if so, find a different place for it.

**Comment by krbz999** [comment]
Doubt anyone feels strongly about this, so I'm determined to simply remove it. This would align with how the system handles effects originated from items that are unequipped/unattuned.

**Comment by InnilToo** [comment]
How will it be handled if some babonus uses it and it will be removed with the new release?

**Comment by krbz999** [comment]
The datamodel should simply ignore fields that are no longer part of it. So if you have `...filters.itemRequirements` in the embedded flag and construct a babonus from it, that single key simply gets fully ignored during construction.
