### ISSUE TITLE
[FEATURE REQUEST] Add the ability to associate an image with each individual bonus

### ISSUE THREAD

**Issue by p4535992** [krbz999/babonus#277]
**Is your feature request related to a problem? Please describe.**

I am using macros and code to handle weapon bonuses in a certain way.

For a purely visual thing , I would like to have the ability to associate an image with each individual bonus, so I can build "prettier" templates with the getCollection method of the api.

**Describe the solution you'd like**

Add in the data object of the bonus the property "img" just like other document, ad a file picker on the ui template.

**Describe alternatives you've considered**

**Setup**

Core Version: 11.307
System: dnd5e 2.3.0 (Atropos) 

**Additional context**

**Comment by tirzah2** [comment]
yes! that would be amazing! Approving XD

**Comment by krbz999** [comment]
Your wording seems to suggest both img and icon. Are you aware of the `Babonus#icon` getter to derive a FA icon associated with the babonus type?

**Comment by p4535992** [comment]
Ok yes I used the word "icon" incorrectly because you already use an icon property with fontawesome for the bonus type right ?

No in my use case I would need new separate image parameter (maybe the easiest solution without touching anything of the current code) , or even make customizable the icon reference if it suits you better .


How best suits you in short.
