### ISSUE TITLE
[FEATURE REQUEST] Option for damage bonus to be assigned a damage type.

### ISSUE THREAD

**Issue by Zanderaf** [krbz999/babonus#283]
An option for the damage bonus section to specify a damage type the bonus is applying might be nice. Few examples could be:
- Item that adds 2d6 cold damage whenever you cast a spell higher than 4th level that deals lightning damage.
- Armor that adds a 1d4 bonus fire damage to all damage rolls made with axe-type weapons.
etc..

**One example I tried to do, an item adding 1d4 damage to spells that deal fire damage, its not clear at all what that extra damage would be. (Image Only taken with BaB active.)**
![example](https://github.com/krbz999/babonus/assets/65571170/9c7f838d-38c2-4e98-85fd-c3182dcf8d66)

**Comment by krbz999** [comment]
This is difficult to do as the system itself quite simply does not support it.

What I personally do is add the damage type as flavor (such as `1d4[fire]`); in core this is nothing more than a label, but I am told most modules support this (as do I in the unreleased 'Damage Application' module). 

Don't hold your breath for this, but I will keep it open as a reminder to implement it when or if the system has better support.
