### ISSUE TITLE
Allow for `abilities` and `saveAbilities` filters to exclude

### ISSUE THREAD

**Issue by DreamingHero1997** [krbz999/babonus#284]
**Is your feature request related to a problem? Please describe.**
Currently the Save DC Ability compares against the Spellcasting ability but this doesn't function as desired in some instances (including mine) where a bonus from another source gets added later to the DC, this ends up giving a bonus when I do not desire it to add a bonus.

**Describe the solution you'd like**
It would be nice if Spellcasting was added as an option to specifically Exclude it from the bonuses as to work nicer with other modules that could affect its DC and for the purpose when you want exclude something that uses the Spellcasting DC.

**Setup**
- 11.2.2
- Foundry V11.308 & DnD5e v2.3.0

**Comment by krbz999** [comment]
Seems to be two requests here; to 'exclude' an ability, and to add 'spellcasting' as an explicit option. I'm gonna frame this issue as a request for the former. The second request will need some clarification with a use case since it's not entirely clear.
