### ISSUE TITLE
[FEATURE REQUEST] - API function to get all applicable baboni to be applied on a potential Roll.

### ISSUE THREAD

**Issue by thatlonelybugbear** [krbz999/babonus#299]
The way Babonus functions, means that when you use the system provided function for instance, `item.getAttackToHit()`, the potential baboni will not be picked up.

This is a request to add an API call to get and display all relevant baboni which would be applied at any potential Roll.

Really basic implementation that leaves a lot to be desired 
```js
const {api} = game.modules.get('babonus');
const itemRolling = /*however you get it*/
const getBabosAttackToHit = api.getType(itemRolling.actor,'attack').map(bab=>bab.bonuses.bonus).join('+');
```

**Comment by krbz999** [comment]
There isn't much to be gained here that would be worth the effort. The use case is rather niche. If you want to make the effort yourself, you could consider manually calling the dnd5e pre-hooks, which will trigger bab's collection methods.
