### ISSUE TITLE
Status Effect Management - Reset to default does not reset

### ISSUE THREAD

**Issue by TheRarita** [krbz999/babonus#30]
When pressing the 'Reset to Default' and confirming, the added statuses do not get removed. 

Also checkbox 'Status Effect Active?' does not save. Even if I uncheck it and close the settings window, open it again, it will stay checked.

I am on v10 latest and have all modules other than 'Tidy UI - Game settings' and 'Module Management +' disabled

**Comment by krbz999** [comment]
Hi, did you post this on the wrong module page?

**Comment by TheRarita** [comment]
yes.... sorry...
