### ISSUE TITLE
[FEATURE REQUEST] Add a transfer property that requires being targeted

### ISSUE THREAD

**Issue by Fridan99** [krbz999/babonus#301]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Perhaps it would be useful to apply a filter so that the bonus only applies to target creatures. There are several class features, spells, and so on, that only affect a certain number of targets.

**Comment by krbz999** [comment]
Seems like a possible inverted candidate similar to #38.
- A bonus taken from targets.
- A bonus taken from targeters.

**Comment by krbz999** [comment]
Would need better use cases to be considered. Wontfix until that happens.
