### ISSUE TITLE
[FEATURE REQUEST] Add option to consume DM Inspiration

### ISSUE THREAD

**Issue by BlackBadger777** [krbz999/babonus#302]
Pretty much what it says on the tint. It would be awesome if bab could use DM Inspiration as a consumable resource. 

Use-case: Mostly homebrew features that make use of Inspiration for something other than simply granting advantage. Making use of Inspiration within BaB in this way would have the added bonus of making DM Inspiration more useful and desirable to gain for players overall. 

As discussed on the Discord server, interaction with vehicles and npcs would have to be taken into consideration, since those don't have an Inspiration field.

- Build-a-Bonus version: 11.4.0
- Foundry core version and build: v11, 308
- DnD5e 2.3.1

**Comment by krbz999** [comment]
The base of this is of course easily doable, the real discussion is how this would interact with auras. However, like optional, consuming auras that target an item's uses/quantity or consumes an effect, the likely way forward is have the aura be valid determined by ownership of the source.
- If the target of an aura cannot delete an effect, then they are an invalid target for this consuming aura.
- If the target of an aura cannot deduct uses/quantity of an item, then they are an invalid target for this consuming aura.
- If the target of an aura cannot toggle off Inspiration on the source actor, then they are an invalid target for this consuming aura.

That logic seems extendable to #264 as well.

**Comment by krbz999** [comment]
Small change of heart on this issue. At least for the initial implementation, the best (most intuitive?) way is for recipients of an aura that consumes GM inspiration to require consuming their own. This is in line with how spell slots, health, and currencies work.

Uses and quantity off items, and effects, are all specific to an individual actor. So it makes sense that just these are outliers.

**Comment by BlackBadger777** [comment]
Agreed, though I'm coming at it from a different pov: Since DM Inspiration is given out by the DM to a specific player, it makes sense that the player can only consume inspiration that they received. If players could consume other players' inspiration, it would (imho), in a way, run counter to the purpose of DM inspiration.
