### ISSUE TITLE
[FEATURE REQUEST] Touching advantages/disadvantages

### ISSUE THREAD

**Issue by rapus95** [krbz999/babonus#310]
## Providing advantages and disadvantages ##

**Is your feature request related to a problem? Please describe.**
I sometimes get lost on tracking advantage and disadvantage. And especially given the filters for conditions regarding vision/senses it would be nice to track advantage/disadvantage. I saw in another issue that this module doesn't touch them so far.

**Describe the solution you'd like**
Have toggles on the bonus tab for advantage/disadvantage.
When opening a roll dialog, right under the text fields, you have the optional bonuses to select.
Right under these just show up as a small text in the form of something like "N advantages, M disadvantages at play" which just sums up the number of effects that are applicable (including activated optional ones) and have one of those toggles set.

So that it looks somewhat like:
```
roll formula | textfield |
bonus | bonus textfield |
[optional babonus]
[reckless babonus - enabled]
1 advantages, 0 disadvantages at play
[Advantage] [Normal] [Disadvantage]
```
So this module doesn't have to decide what button to press, but just helps to track circumstances. Optionally include a list of babonuses where the advantages and disadvantages originate from. Maybe as a tooltip.

**Describe alternatives you've considered**
Since no other modules I know fiddle with the roll dialog, I have no other ideas where that could fit into.

## Filtering for advantages and disadvantages ##

**Is your feature request related to a problem? Please describe.**
It would be nice to be able to for example have sneak attack automatically applied when the roll was made with advantage. 

**Describe the solution you'd like**
Given that it's difficult to know what the corresponding roll was, I instead suggest adding an input field to for example damage rolls, where you can select advantage/disadvantage to refer to how the roll was made. In the babonus config this could be referred to with a new corresponding filter option.

Damage Roll Dialog could look like:
```
roll formula | textfield |
bonus | bonus textfield |
[X Advantage] [Disadvantage]
[optional babonus]
[sneak attack babonus - applied]
[Crit] [Normal]
```

**Comment by krbz999** [comment]
It is intentional that this module does not touch advantage and disadvantage. These are concepts that are left for DM fiat, and moreover the scope of babonus is already quite broad despite limiting itself to 'filtering bonuses'. Also serving as a reminder for advantage and disadvantage would be an unneeded increase in scope.

However, you can make a "reminder" using babonus by making it optional with a dummy bonus such as "0" or some invalid roll data property.

**Comment by rapus95** [comment]
that's unfortunate given it is a direct roll bonus and affects exactly those things within this modules scope :/
But i like your suggestion regarding an optional 0 bonus. Ty. With that in mind having a new roll modifier type field (or the ability to add some) on the bonus tab would already solve it entirely.

**Comment by krbz999** [comment]
There are many more reasons - both gameplay reasons as well as technical reasons - why adv/disadv are not a consideration and are beyond the scope of this module.
