### ISSUE TITLE
Bonuses on vehicles are always suppressed due to their inability to attune or equip, and 'crewed' being ignored properties

### ISSUE THREAD

**Issue by XXDarrienX** [krbz999/babonus#315]
**Describe the bug**
None of the build a bonus created on vehicle sheets will do anything, if you create a vehicle weapon and just put it on a normal acto sheet the bonus works but once its on a vehicle sheet it does nothing.

**To Reproduce**
1. Create a Vehicle Sheet in 5E
2. Create a Weapon on the Vehicle
3. Create a simple bonus for it to automatically apply without filters
4. No bonus effects

**Expected behavior**
The bonus should work like it does on actor sheets

**Screenshots**
Screenshots attached

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 11.4.2
- Foundry core version and build: 11.315
- Other modules disabled? No

![image](https://github.com/krbz999/babonus/assets/28017703/11d3bc51-9f05-4dd2-8247-b6f33d08b636)
![image](https://github.com/krbz999/babonus/assets/28017703/9f167221-a36d-4737-9a40-8610769e76d9)
![image](https://github.com/krbz999/babonus/assets/28017703/d52d4819-5a6f-40a6-83bd-22eeb2d02944)

**Comment by krbz999** [comment]
> * Other modules disabled? No

Do that.

**Comment by krbz999** [comment]
I've gone ahead and found the actual issue in a single-module environment for you. Please disable all irrelevant modules in the future before making bug reports.
