### ISSUE TITLE
Shield Armor Types key does not work  [BUG]

### ISSUE THREAD

**Issue by chilynthe** [krbz999/babonus#346]
**Describe the bug**
When using the Armor Types filter set to Include the shield key, no bonus is registered. No otter appears in the roll dialogue header and no bonus is applied. Testing with other armor types, such as chain mail, has worked properly, thus far. 

**To Reproduce**
1. On the Feature Item, go to Saving Throws and add a bonus 
2. Click on Filters and Armor Types and Saving Throw Types then head to Configuration 
3. Click Keys in Armor Types, select Include for Shields, select Keys for Saving Throws, pick any or all to Include and apply (make sure the bonus is enabled)
4. Make sure you have a shield equipped and click on the chosen Saving Throw(s) on the character sheet 
5. Nothing happens -- if you follow the same steps with Chain Shirt as your Armor Types key, everything works as expected 
6. The same issue occurs if you choose the Shield key with Attack Bonus 

**Expected behavior**
With an equipped shield, when you click the saving throw, the babonus otter should appear in the roll dialogue and the bonus should be applied. 

**Screenshots**
![Screenshot 2024-02-21 175438](https://github.com/krbz999/babonus/assets/94516408/72d365ec-ede5-459c-be13-7b030a3d0e5b)
![Screenshot 2024-02-21 180346](https://github.com/krbz999/babonus/assets/94516408/cd3dcb41-2906-4aca-af42-ef1ae1112da3)
![Screenshot 2024-02-21 175532](https://github.com/krbz999/babonus/assets/94516408/a07a325b-ea99-4482-b31c-004f974635d7)
![Screenshot 2024-02-21 175548](https://github.com/krbz999/babonus/assets/94516408/a822cf3b-564b-4f83-997d-e957da4b3f58)
![Screenshot 2024-02-21 175625](https://github.com/krbz999/babonus/assets/94516408/1bf3ee43-b682-428c-bf95-0926ecf94e8d)

![Screenshot 2024-02-21 180439](https://github.com/krbz999/babonus/assets/94516408/5b37e770-5b75-45fc-9961-35b630474439)
![Screenshot 2024-02-21 175644](https://github.com/krbz999/babonus/assets/94516408/d185ff91-2029-43e8-9409-e5ef79515338)
![Screenshot 2024-02-21 180520](https://github.com/krbz999/babonus/assets/94516408/e3a47ea5-e54d-48cb-aca0-c50e2ed86bff)
![Screenshot 2024-02-21 180528](https://github.com/krbz999/babonus/assets/94516408/eca932fb-f300-4ebb-939f-7d2d3b8f32e1)

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 11.8.0
- Foundry core version and build: v11 Stable 315
- Other modules disabled? No

**Additional context**

**Comment by krbz999** [comment]
Since with v3 shields can have a `baseItem` same as armor, it would be good to support this explicitly. That does mean it should be expected that users set up basic shields to have the 'Shield' `baseItem`, same as the SRD shields.

This has the benefit of simplifying some of the code in the module, on top of fixing this issue. Seems like the filter has not been working for who knows how long if an actor was wearing a shield but no armor.

**Comment by krbz999** [comment]
Will be fixed in the 11.9 update.
