### ISSUE TITLE
[FEATURE REQUEST]: BaB-TaB Improvements / Suggestions?

### ISSUE THREAD

**Issue by Zanderaf** [krbz999/babonus#352]
Got one or two suggestions for the BaBTaB that came to mind. Mainly having the tab show every babonus currently actively affecting the actor, from features / items / maybe auras?

**Comment by krbz999** [comment]
Auras won't be doable, since an actor is only conditionally under the effect of another actor's aura, and this is only known during the roll.

Showing every embedded document's bonuses on the tab of the character is perfectly doable though.
