### ISSUE TITLE
Allow an aura to be restricted by obstructions that block sound

### ISSUE THREAD

**Issue by krbz999** [krbz999/babonus#353]

**Comment by GamerFlix** [comment]
Consider adding light and/or sight while you are at it.
The former is quite common, the löatter could be useful for stuff like daylight spells.

**Comment by krbz999** [comment]
Sight and movement were already able to restrict an aura.

Light is a different beast to figure out how it should restrict an aura, if at all.

**Comment by GamerFlix** [comment]
Was mainly talking about light restricting walls restricting things instead of the light source itself having any influence. Mainly mentioned it due to similar logic being involved.

**Comment by krbz999** [comment]
Hm yeah I suppose you could have an 'aura of light', with an actual lighting effect on the token being used to visualize it.
