### ISSUE TITLE
[BUG] Optional Bab on ability checks, saves, and other bab options seems to error out

### ISSUE THREAD

**Issue by Zanderaf** [krbz999/babonus#368]
**Describe the bug**
Optional Bab on ability checks doesnt seem to work, looks like to be all optional babs at this point.

**To Reproduce**
1. Make 1d4 optional bab for ability checks
2. roll, it errors out

**Screenshots**
![Capture](https://github.com/krbz999/babonus/assets/65571170/aa7e4ee2-57c0-4c51-a49b-e51c474e61b3)

**Setup**
Describe your foundry setup.
- Build-a-Bonus version:  11.9.1
- Foundry core version and build:  11.315
- Other modules disabled? Yes/No yes

**Additional context**

**Comment by krbz999** [comment]
Oh this one is stupid...
