### ISSUE TITLE
[BUG] Error when deleting recently created bonus

### ISSUE THREAD

**Issue by etiquettestartshere** [krbz999/babonus#372]
**Describe the bug**
An error is thrown when creating a bonus and deleting it without reloading.

**To Reproduce**
1. Open an actor sheet (I reproduced this behavior without the 'Character Sheet Tab' setting, with Morthos (Tiefling Sorcerer)), and create a new bonus in any category on either an item or the actor. The bonus may or may not be blank.
2. Immediately delete the bonus. 

**Expected behavior**
If no reload has taken place before the deletion of the new effect, an error is thrown by foundry.js.

**Screenshots**
![image](https://github.com/krbz999/babonus/assets/148253744/c45db48b-5c83-43fe-a3c6-6c9fc144fc48)

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 11.9.2
- Foundry core version and build: 315Version 11 Stable
- dnd5e system version: 3.0.4
- Other modules enabled? No

**Comment by krbz999** [comment]
Is this preventing the sheet from closing?

**Comment by etiquettestartshere** [comment]
Not that I've found (not for any of the sheets involved)
