### ISSUE TITLE
Scaling exploding damage dice through an optional bonus strips dice modifiers

### ISSUE THREAD

**Issue by Zanderaf** [krbz999/babonus#375]
**Describe the bug**
As title says, doing a damage bonus of 2d4x that deals an additional 2d4x on every increased step of the bonus causes it to lose the "x" part of the formula.

**To Reproduce**
1. Make a damage bonus bab that deals 2d4x cold damage
2. Make it optional with limited use consumption, and leave the scaling formula blank (at base it should be a grayed out 2d4x)
3. Roll it at base 2d4x, it works, increase the step by 1, it just goes to 4d4
4. See previous step

**Expected behavior**
Expected to go to 4d4x, 6d6x, etc

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 11.9.2
- Foundry core version and build: 11.315
- Other modules disabled? Yes/No

**Comment by krbz999** [comment]
Apparently a system issue.

https://github.com/foundryvtt/dnd5e/issues/3263

**Comment by krbz999** [comment]
Confirmed to be fixed by dnd5e v3.1.2.
