### ISSUE TITLE
[BUG] Select dropdowns have black text on dark background in some conditions

### ISSUE THREAD

**Issue by etiquettestartshere** [krbz999/babonus#384]
**Describe the bug**
Select dropdowns for build a bonus filters, such as Feature Types or the comparison operator select for Arbitrary Comparison have black text on dark backgrounds. I am unsure of the cause, but my guess would be something to do with the new system dark theme referencing the current windows theme (just a guess, may be unrelated).

**To Reproduce**
0?. Set Windows (10?) theme to dark mode
1. Add a new damage bab
2. Add a Feature Types filter
3. Open the select dropdown
4. Text is black on a dark background

**Screenshots**
![image](https://github.com/krbz999/babonus/assets/148253744/a76c72c0-34b4-4673-88a8-2532dd664510)

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 11.9.4
- dnd5e system version: 3.1.1
- Foundry core version and build: 315Version 11 Stable
- Other modules disabled? Yes (all other modules are disabled)
___
- Google Chrome Version: 123.0.6312.86 (Official Build) (64-bit) (No Browser Extensions)
- Windows 10 Version: 22H2

**Comment by Zanderaf** [comment]
Yea i've had this happen to me too with just BAB in a fresh world
