### ISSUE TITLE
[BUG] Text editors are not properly enriching the `lookup` enricher.

### ISSUE THREAD

**Issue by Zanderaf** [krbz999/babonus#398]
**Describe the bug**
Lookup Enrichers dont pass properly in an optional bab/in bab at all. So something like [[lookup @ name]] for a creature will just be @ name when saved.
**To Reproduce**
type [[lookup @ name]] in an optional bab and trigger it, should look like the below screenshot.

**Expected behavior**
Display the actors name instead of @ name

**Screenshots**
![image](https://github.com/krbz999/babonus/assets/65571170/47b053eb-efdc-4422-bfc4-e7345b274e67)
**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 11.10
- Foundry core version and build: 11-315
- Other modules disabled? Yes/No

**Additional context**

**Comment by krbz999** [comment]
Seems like a missing `relativeTo` in all instances of `TextEditor.enrichHTML`.
