### ISSUE TITLE
[BUG] D&D Version 3.2.0 required but isn't available yet

### ISSUE THREAD

**Issue by Stormthirst** [krbz999/babonus#413]
**Describe the bug**
Module is reporting that version 3.2.0 of D&D is required, but isn't on general release yet.

**Comment by kajishun** [comment]
+1

**Comment by markmillerlv** [comment]
Following due to same issue.

**Comment by markmillerlv** [comment]
I uninstalled and reinstalled older JSON module file: https://github.com/krbz999/babonus/releases/download/v11.10.6/module.json
It seems to have fixed the issue and let me reactivate the Build A Bonus module.

**Comment by kajishun** [comment]
> I uninstalled and reinstalled older JSON module file: https://github.com/krbz999/babonus/releases/download/v11.10.6/module.json It seems to have fixed the issue and let me reactivate the Build A Bonus module.

good tip, thanks!

**Comment by krbz999** [comment]
There isn't an issue here.
