### ISSUE TITLE
[BUG] Hard to see the tab icons and labels on the BaB sheet

### ISSUE THREAD

**Issue by kaelad02** [krbz999/babonus#438]
**Describe the bug**
I created a new Attack Roll bonus and it brought up a sheet to configure it. There's a styling issue and it's really hard to see the tabs on the sheet.

**To Reproduce**
1. create a new item
2. click on the BAB header button
3. create a new Attack Roll bonus

**Expected behavior**
The tab icons and labels should be easy to see, in black in my case.

**Screenshots**
![image](https://github.com/krbz999/babonus/assets/19502084/90dbecae-94b1-44b7-a474-efc45b4328ae)

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 12.0.5
- Foundry core version and build: 12.327
- Other modules disabled? Yes

**Additional context**
I suspect it's an issue with the browser and core setting being in Light mode. The styling for the tab icons and labels would probably look fine in Dark mode, but I'm currently working in Light mode.

**Comment by krbz999** [comment]
Core issue.

https://github.com/foundryvtt/foundryvtt/issues/11290
