### ISSUE TITLE
Module is not activating in Foundry V11 after v3.3 update

### ISSUE THREAD

**Issue by jtgeraldes** [krbz999/babonus#440]
**Describe the bug**
The module is automatically disabled and cannot be activated on Foundry v11 after DnD5e V3.3 update

There is a lock saying the module is compatible with DnD5e up to V3.2.9. The system is compatible with V3.3 according to the release notes, but requires Foundry V12 to update. However, many modules that rely on BaB, like CPR are still not V12 compatible.

**Comment by krbz999** [comment]
Not a bug.

**Comment by msalafia** [comment]
@krbz999 But will babonus be available on V11 with dnd5e 3.3?

**Comment by krbz999** [comment]
No.
