### ISSUE TITLE
[BUG] Build-a-bonus affects localizations

### ISSUE THREAD

**Issue by BrotherSharper** [krbz999/babonus#443]
**Describe the bug**
When build a bonus is enabled, individual weapons, armor, tools are reverted to english.
These categories are linked to item IDs which are localized via babele in the compendium entries.

If build-a-bonus is changing any of the item IDs, this would break localizations via babele.
This is a bit obscure and I am unable to know why bab would even do this.

**To Reproduce**
1. Install any language mod that uses babele 
2. Open any of the starter heroes
3. Check any character that has tools or individual proficiencies
4. No error log is shown

**Expected behavior**
Foundry should be able to accurately get the name of each entry from compendiums.

**Screenshots**
![image](https://github.com/user-attachments/assets/e1bb078d-0dda-4691-832f-a11aa538d750)

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 12.1.3
- Foundry core version and build: V12 Build 331
- Other modules disabled? Yes (Found using "find the culprit")

**Additional context**
None

**Comment by krbz999** [comment]
See #396, as well as your own issue on the system repo here: https://github.com/foundryvtt/dnd5e/issues/3587.

I already know why this happens, it's because babonus calls a system method that accesses the compendiums. However, why this affects localization is an issue with babele.

**Comment by krbz999** [comment]
> If build-a-bonus is changing any of the item IDs, this would break localizations via babele.

To be very clear, bab is NOT doing this.

**Comment by BrotherSharper** [comment]
Ah, thank you
I will check on babele and see if I can bring it over there
