### ISSUE TITLE
Bonus not applying

### ISSUE THREAD

**Issue by maxobremer** [krbz999/babonus#46]
So the bonus on the left (see image) doesnt apply while the bonus on the right does apply?
(the description and stuff on the right says penalty because I intend to make it a penalty.)
both come from a different wand, that have no mayor differences (one has some spells from items with spells and 2 charges but thats it) 
![image](https://user-images.githubusercontent.com/86924581/194761447-ea10558f-002a-4f42-a2bd-fe83d0602f2f.png)

**Comment by maxobremer** [comment]
the daggers of damocles spell is a divination spell fyi

**Comment by maxobremer** [comment]
also tested it without any modules that affect or speed up rolls. (disabled ready steady roll module and rolled the fire damage again after making the screenshot from before which still did nothing)

**Comment by krbz999** [comment]
It seems the previous bugfix update saves an array of empty strings when you have no status effects as filters...

Should be a quick and easy fix. Thank you.
