### ISSUE TITLE
Implement a generic 'tags' filter

### ISSUE THREAD

**Issue by krbz999** [krbz999/babonus#463]
This filter would
- retrieve an array of string tags on the actor performing a roll, and the item being used, if any, as well as any applied active effects on the actor (or item),
- Retrieve an array of string tags on the target.
- compare to a set of strings on the bab.

Should be a decent stand-in for the more restrictive `ActiveEffect#statuses` set.

**Comment by GamerFlix** [comment]
I'd suggest choosing a different name to avoid users confusing the feature with a [Tagger](https://foundryvtt.com/packages/tagger) integration.

**Comment by krbz999** [comment]
Such as?

**Comment by GamerFlix** [comment]
"marker" would be an option. Alternatively if what gets checked is preset omitting a name in favor of "miscellanious filters" or smth along those lines might be doable.

**Comment by krbz999** [comment]
![image](https://github.com/user-attachments/assets/65ea2468-8796-4042-b38e-fff2423fa6aa)
