### ISSUE TITLE
[BUG] Damage type not applying and bonus's not always triggering for all dmg

### ISSUE THREAD

**Issue by robgrahamau** [krbz999/babonus#468]
**Describe the bug**
When building a bonus and adding it on damage type in the recent versions it is not applying it as the selected damage type but as what ever the first damage type on the item is set to. Were as in previous versions it did.

**To Reproduce**
Create an object, go into Build a bonus set up a damage type example 
![image](https://github.com/user-attachments/assets/6ebe8c38-fd4a-4961-996b-3b9dbe2c8b7a)

![image](https://github.com/user-attachments/assets/b6680665-bef1-46e2-8952-2f7ccb4956e7)

Using the item/weapon do a damage roll 
![image](https://github.com/user-attachments/assets/82ce9950-0350-43e0-bc6d-985bd715e80a)
apply the radiant damage (in this case)
![image](https://github.com/user-attachments/assets/b65eb229-1c75-4405-a1e1-a0099c9a9f48)
Note that it has not added it as radiant but as Bludgeoning damage, despite being set to radiant
![image](https://github.com/user-attachments/assets/f2021d91-a7db-4163-8494-0658c50f1099)

**Expected behavior**
Damage should be applying as set in the bonus as it did before.

**Setup**
Describe your foundry setup.
- Build-a-Bonus version:  12.4.2
- Foundry core version and build: v12 331
- Other modules disabled? Yes
- D&D 4.0.4

It also appears that some other bonus's may not be applying correctly as they used to as well. Example explosive is now not triggering for all damage just the first line etc.

**Comment by krbz999** [comment]
Seems like it was specifically a small oversight when the bonus is optional.
