### ISSUE TITLE
[BUG] Explosive etc not adding if a damage type is optional.

### ISSUE THREAD

**Issue by robgrahamau** [krbz999/babonus#469]
**Describe the bug**
If you have an option damage bonus along with an explosive or any other type of modifier that is its own Bonus

**To Reproduce**
![image](https://github.com/user-attachments/assets/668d8f85-cb94-4916-9141-6f9486c7d868)
Here we can see we have explosive which is set to reroll 2 or higher 
![image](https://github.com/user-attachments/assets/3d3c14eb-3cc3-4602-a709-9fee0020406f)
along with an option psychic damage add
![image](https://github.com/user-attachments/assets/c77fbb9b-d76e-4d58-ada0-82051da56bb9)
![image](https://github.com/user-attachments/assets/a1f3f1a0-5031-4298-87b2-1f129354aa05)

When you roll and ADD the optional damage the explosive bonus is not being added to the optional damage

![image](https://github.com/user-attachments/assets/e6969976-6efd-4e82-a9cf-44f3f951024f)

![image](https://github.com/user-attachments/assets/150e3adc-4d48-4982-9e64-a4adfbc5e5c1)

**Expected behavior**
Explosive etc should be applying to the optional damage as well.

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 12.4.3
- Foundry core version and build: 12 331
- Other modules disabled? Yes

**Additional context**
Believe related to the optional bug just solved, but this segment missed.

**Comment by krbz999** [comment]
Something more intelligent is needed for applying dice modifiers. This has to happen in multiple stages since all dice modifiers have to come after application of all the additive bonuses, optional or not.

**Comment by robgrahamau** [comment]
If there's anything I can do to help let me know,  also sorry that I seem to be doing things in niche ways that keeps finding edge cases, its just that I really like how bab let's me make very unique magical items or help automate things for my players etc.
