### ISSUE TITLE
[BUG] Exploding dice rolls don't work

### ISSUE THREAD

**Issue by mkevans80** [krbz999/babonus#475]
Exploding dice bonus does not appear to work.

1. Go into a dagger, make a damage BaB.
2. Select "Exploding dice" set to a threshold of 3.
3. Roll damage, dice rolls of 3 or 4 do not explode.
4. No errors are found in the console.

- Build-a-Bonus version:  12.5.3
- Foundry core version and build: 12.331, Dnd5e 4.0.4
- Other modules disabled? Yes

**Comment by krbz999** [comment]
Was not able to reproduce this. Make sure the weapon is actually equipped; bonuses on items that are not equipped, attuned (if required), or crewed (on a vehicle) will be ignored.

**Comment by mkevans80** [comment]
Ah, it was not equipped, so that explains it.  Thank you and sorry for the false alarm!
