### ISSUE TITLE
Item Types filter does not populate the available filters section correctly

### ISSUE THREAD

**Issue by rinnocenti** [krbz999/babonus#72]
I start with a request for new functionality: being able to create bonuses for movement and armor class.

The bug, I'm trying to create a bonus only when using a weapon type (longbow in case).

But the filter is invalid even saying it should be active for bous on attack roll
![Captura de tela 2022-11-11 155952](https://user-images.githubusercontent.com/3178127/201411875-73a968d9-d214-4892-a1d7-4f48ece8f69e.png)

**Comment by krbz999** [comment]
Seems like something broke with the item types filter, not allowing spells-only or weapons-only filters being moved to the available section.

**Comment by InnilToo** [comment]
Wouldn't the arbitrary comparison suffice when dealing with AC and movement? You can compare value so if you want to have a bonus on flying creatures compare if their flying speed is higher than 0. Haven't tested it myself yet.

**Comment by krbz999** [comment]
AC and movement would be a separate issue or request.
