### ISSUE TITLE
Clearly label the supported system(s)

### ISSUE THREAD

**Issue by Truncated** [krbz999/babonus#79]
I've scoured the entire descriptions but couldn't find anything that told me whether this was meant to be system agnostic or is actually locked / supported specific systems. I infer 5e, but that's based on examples that could just as easily be meant to be more broadly interpreted.

So, when I load this in:
![image](https://user-images.githubusercontent.com/14208325/202570101-24c37a1a-6b65-4525-afc4-21dbcea68b54.png)

It does not show up in the Module list for my world. :(

If it's a bug, I don't get any erorr in the console from it.

If it's not a bug, please consider support for PF1e and some kind of clear update in the Read Me for officially supported systems as my enhancement request.

Thanks!

**Comment by krbz999** [comment]
The module is only available for dnd5e.

**Comment by Truncated** [comment]
Bullocks. :)

Congrats on the Package Jam win, though! Well deserved.
