### ISSUE TITLE
Expose filters in API for macros and modules to use

### ISSUE THREAD

**Issue by GhostwheelX** [krbz999/babonus#80]
Might it be possible to use DAE in conjunction with BAB to apply effects? I think it could be really cool to create things like stun on crit or grapple only certain types of monsters, etc.

Plus it would make it easy to automate feats like Crusher or Slasher from Tasha's.

**Comment by krbz999** [comment]
Since this would be vastly out of scope of Build-a-Bonus, and since Midi-QOL compatibility is far from a priority, what I can look into doing is exposing the filter functions such that any script writer can perform these actions themselves.
