### ISSUE TITLE
Feature Request: Add a toggleable `itemOnly` property that restricts a bonus to only apply to the item on which it is created

### ISSUE THREAD

**Issue by harrisog** [krbz999/babonus#81]
It would be great if we could slap a babonus on a weapon and set it up so that it apples only to rolls made with that weapon

**Comment by InnilToo** [comment]
This can be done through filters, which isn't as easy as checking a box that says "This item only" but it's possible. Unless you have two identical weapons on you.

**Comment by harrisog** [comment]
could you post an example please?

**Comment by krbz999** [comment]
You can narrow the filters down such that it is very likely to only apply to the weapon in question. However I think that this is a legitimate use case that warrants an explicit property.
