### ISSUE TITLE
Feature request: Support drag and drop between two babonus sheets

### ISSUE THREAD

**Issue by InnilToo** [krbz999/babonus#85]
It would be handy not to have to recreate whole bonus from scratch and just be able to copy it to a new actor/item/feature.

**Comment by krbz999** [comment]
```js
const api = game.modules.get("babonus").api;
const original = await fromUuid("uuid of original document of bonus");
const target = await fromUuid("uuid of target document here");
await api.copyBonus(original, target, "id of bonus to copy");
```

**Comment by thatlonelybugbear** [comment]
Could that be something doable when dnd5e 2.1.xx drops?
https://github.com/foundryvtt/dnd5e/pull/1766

**Comment by krbz999** [comment]
> Could that be something doable when dnd5e 2.1.xx drops?

Babonus doesn't change the sheets themselves in any capacity, so any drag-and-drop would be implemented on the module's end, meaning that PR isn't relevant. Regardless, it's going to remain a `#wontfix` at least for the time being as using the API is considered an 'advanced' feature for users specifically intending to use it as such.
